.github/workflows/node.js.yml, src/front-end/package-lock.json, src/front-end/package.json, src/front-end/src/App.tsx, src/front-end/src/components/auth/loginPage.tsx, src/front-end/src/theme.tsx
=> feat: Create original verion of Login Page component

src/front-end/src/App.tsx, src/front-end/src/components/auth/createAccPage.tsx, src/front-end/src/docs/theme.md
=> feat: create acc page finished

src/front-end/src/App.tsx, src/front-end/src/components/onboard/personinfo.tsx, src/front-end/src/components/onboard/reference.tsx
=> feat: reference info page finished

src/front-end/src/App.tsx, src/front-end/src/components/onboard/EmergencyContact.tsx, src/front-end/src/components/onboard/Personinfo.tsx, src/front-end/src/components/onboard/Reference.tsx
=> feat: emergency contact finished

src/front-end/src/App.tsx, src/front-end/src/components/common/Footer.tsx, src/front-end/src/components/onboard/OnBoardingSteper.tsx
=> feat: add footer and onboarding stepper page

src/front-end/src/App.tsx, src/front-end/src/components/employee/dashboard/layout.tsx, src/front-end/src/components/employee/dashboard/sideNav.tsx, src/front-end/src/components/hr/HrEmployeeProfiles.tsx, src/front-end/src/components/hr/HrSideNavItems.tsx
=> refactor: add role to Layout for employee & hr

src/front-end/src/components/employee/EmployeeProfile.tsx, src/front-end/src/components/employee/dashboard/layout.tsx
=> feat: add employee profile page

src/front-end/src/components/employee/ApplicantStatus.tsx, src/front-end/src/components/employee/ApplicationStatus.tsx, src/front-end/src/components/employee/EmployeeHome.tsx
=> refactor: encapsulate applicant status to 1 component

src/front-end/src/App.tsx, src/front-end/src/components/employee/EmployeeProfile.tsx, src/front-end/src/components/employee/EmployeeVisaManagement.tsx
=> feat: add employee visa management page

src/front-end/src/components/hr/EmployeeCard.tsx, src/front-end/src/components/hr/HrEmployeeProfiles.tsx, src/front-end/src/components/hr/TableSearch.tsx, src/front-end/src/styles/hr/profile.tsx, src/front-end/src/theme.tsx
=> Feat: HR's Employee Dashboard desktop and mobile version Frontend

src/front-end/src/App.tsx, src/front-end/src/components/hr/HrEmployeeProfiles.tsx, src/front-end/src/components/hr/ProfileScreen.tsx, src/front-end/src/components/hr/other/Document.tsx, src/front-end/src/components/hr/profile/profileElements.tsx, src/front-end/src/styles/hr/profile.tsx
=> Feat: Create employee profile detail page

src/back-end/.gitignore, src/back-end/package-lock.json, src/back-end/package.json, src/back-end/src/app.ts, src/back-end/src/config/mailConfig.ts
=> feat: add mail servies

src/back-end/src/models/OnboardingApplication.ts, src/back-end/src/models/PersonalInformation.ts, src/back-end/src/models/RegistrationToken.ts, src/back-end/src/models/User.ts, src/back-end/src/models/VisaStatus.ts
=> refactor: refactor back end schema

src/back-end/package-lock.json, src/back-end/package.json, src/back-end/src/config/registTokenGen.ts, src/back-end/src/controllers/hrController.ts
=> feat: token generator

src/back-end/src/testdata/createHRManagement.ts, src/back-end/src/testdata/createHRUser.ts, src/back-end/src/testdata/createOPTEmployee.ts, src/back-end/src/testdata/createRegistartionToken.ts
#36 has been resolved 🚀 
1. 
2. 
3. 
=> bug: change env

src/back-end/src/models/PersonalInformation.ts, src/back-end/src/testdata/createHRUser.ts, src/back-end/src/testdata/createOPTEmployee.ts
=> fix: added ssn and reference to model

src/back-end/src/config/mailConfig.ts, src/back-end/src/controllers/userController.ts, src/front-end/package-lock.json, src/front-end/package.json, src/front-end/src/App.tsx, src/front-end/src/components/auth/AuthLayout.tsx, src/front-end/src/components/auth/CreateAccPage.tsx, src/front-end/src/components/auth/LoginPage.tsx, src/front-end/src/components/auth/RouteProtector.tsx, src/front-end/src/components/onboard/BasicInfo.tsx, src/front-end/src/components/onboard/EmergencyContact.tsx, src/front-end/src/components/onboard/OnboardingLayout.tsx, src/front-end/src/components/onboard/Personinfo.tsx, src/front-end/src/components/onboard/Reference.tsx, src/front-end/src/components/onboard/Summary.tsx, src/front-end/src/components/onboard/UserContext.tsx
=> feat: the Router Protection of Front end finished

src/back-end/src/app.ts, src/back-end/src/controllers/RegistrationTokenController.ts, src/back-end/src/routes/verifyRoutes.ts, src/front-end/package-lock.json, src/front-end/package.json, src/front-end/src/App.test.tsx, src/front-end/src/components/auth/CreateAccPage.tsx, src/front-end/src/components/auth/RouteProtector.tsx, src/front-end/src/test/onboard/EmergencyContact.test.tsx
=> debug: upload u test example with jest lib

src/back-end/src/app.ts, src/back-end/src/config/authToken.ts, src/back-end/src/config/s3MulterConfig.ts, src/back-end/src/controllers/personalInfoController.ts, src/back-end/src/controllers/userController.ts, src/back-end/src/controllers/visaController.ts, src/back-end/src/models/RegistrationToken.ts, src/back-end/src/models/VisaStatus.ts, src/back-end/src/routes/personalInfoRoutes.ts, src/front-end/package-lock.json, src/front-end/package.json, src/front-end/src/components/employee/EmployeeProfile.tsx, src/front-end/src/components/employee/EmployeeVisaManagement.tsx, src/front-end/src/components/employee/common/UploadFileButton.tsx, src/front-end/src/components/employee/dashboard/topNav.tsx
1. 
2. 
3. 
- [] I have updated the documentation accordingly.
=> feat & bug & refactor: route protection and logout and upload file

src/back-end/src/controllers/hrController.ts, src/back-end/src/routes/hrRoutes.ts, src/front-end/src/App.tsx, src/front-end/src/components/hr/common/ApplicationDecision.tsx, src/front-end/src/components/hr/data/hiring/EmployeeDataInterfaces.ts, src/front-end/src/components/hr/data/hiring/hiringDataTransformUtils.ts, src/front-end/src/components/hr/hiring/HrEmployeeApplication.tsx, src/front-end/src/components/hr/hiring/HrHiringManagement.tsx, src/front-end/src/components/hr/utils/utils.tsx, src/front-end/src/redux/features/hr/hrSlice.ts, src/front-end/src/redux/features/hr/hrTypes.ts, src/front-end/src/redux/features/hr/onboardSlice.ts
=> feat: add decision button in application

src/back-end/src/controllers/RegistrationTokenController.ts, src/back-end/src/controllers/userController.ts, src/back-end/src/routes/personalInfoRoutes.ts, src/front-end/src/components/auth/CreateAccPage.tsx, src/front-end/src/components/onboard/BasicInfo.tsx, src/front-end/src/components/onboard/Summary.tsx
=> refactor: put method update

src/front-end/src/components/onboard/Summary.tsx
=> refactor: emergency contact can work right now

src/front-end/src/components/employee/common/UploadFileButton.tsx, src/front-end/src/components/onboard/BasicInfo.tsx, src/front-end/src/components/onboard/uploadFile.tsx
=> refactor & bug : upload button

src/front-end/src/App.tsx
=> refact: route protection

src/back-end/src/controllers/hrController.ts, src/back-end/src/models/VisaStatus.ts, src/front-end/src/components/hr/common/FileDecision.tsx
=> fix: change all "accepted" to "approved" and other small bug fix

src/front-end/src/components/employee/EmployeeProfile.tsx, src/front-end/src/components/employee/EmployeeVisaManagement.tsx, src/front-end/src/components/employee/common/UploadFileButton.tsx
=> bug: upload files formats
